name: Latest YouTube Videos
on:
  schedule:
    # Runs every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to run it manually to test

permissions:
  contents: write

jobs:
  update-readme:
    name: Update this readme with latest videos
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Fetch YouTube Videos
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE-CARDS"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCZFJskZ1dzmubbKzqtewRhQ"
          max_post_count: 3
          template: '<a href="$url" target="_blank" style="margin-right: 15px;"><img src="$imgUrl" alt="$title" width="220" style="border-radius: 6px; border: 1px solid #3c3836;" /></a>'